# Generated by Django 5.2.16 on 2026-08-01 22:08

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationDeliveryModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("notification_type", models.CharField(max_length=80)),
                ("recipient_lookup_hmac", models.CharField(db_index=True, max_length=64)),
                ("task_id", models.CharField(db_index=True, max_length=255)),
                ("attempt_number", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROCESSING", "Processing"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=160)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "notification_deliveries",
                "ordering": ["-started_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("task_id", "attempt_number"),
                        name="uq_notification_delivery_task_attempt",
                    )
                ],
            },
        ),
    ]
