# Generated by Django 5.2.16 on 2026-08-02 03:03

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileVersionModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("checksum_algorithm", models.CharField(max_length=24)),
                ("checksum_digest", models.CharField(max_length=128)),
                ("source_machine_id", models.UUIDField(blank=True, null=True)),
                ("source_reference", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "file_versions",
            },
        ),
        migrations.CreateModel(
            name="MediaFileModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("project_id", models.UUIDField(db_index=True)),
                ("created_by_user_id", models.UUIDField(db_index=True)),
                ("original_name", models.CharField(max_length=255)),
                ("display_name", models.CharField(max_length=255)),
                ("extension", models.CharField(blank=True, max_length=32)),
                ("media_type", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                ("observations", models.TextField(blank=True)),
                ("recorded_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(db_index=True, default="DESCOBERTO", max_length=40)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "media_files",
                "ordering": ["display_name", "id"],
            },
        ),
        migrations.CreateModel(
            name="DriveObjectModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("provider", models.CharField(default="GOOGLE_DRIVE", max_length=32)),
                ("external_id", models.CharField(blank=True, max_length=255)),
                ("object_reference", models.CharField(blank=True, max_length=512)),
                ("status", models.CharField(default="PENDING", max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="storage_objects",
                        to="catalog.fileversionmodel",
                    ),
                ),
            ],
            options={
                "db_table": "drive_objects",
            },
        ),
        migrations.AddField(
            model_name="fileversionmodel",
            name="media_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="physical_versions",
                to="catalog.mediafilemodel",
            ),
        ),
        migrations.AddConstraint(
            model_name="fileversionmodel",
            constraint=models.UniqueConstraint(
                fields=("media_file", "sequence"), name="uq_file_version_sequence"
            ),
        ),
    ]
