# Generated by Django 5.2.16 on 2026-08-02 04:10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetadataVersionModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.PositiveBigIntegerField()),
                ("actor_user_id", models.UUIDField(db_index=True)),
                ("snapshot", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "media_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="metadata_versions",
                        to="catalog.mediafilemodel",
                    ),
                ),
            ],
            options={
                "db_table": "metadata_versions",
                "ordering": ["version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("media_file", "version"), name="uq_metadata_version_number"
                    )
                ],
            },
        ),
    ]
