from enum import StrEnum


class MediaFileStatus(StrEnum):
    DISCOVERED = "DESCOBERTO"
    ANALYZED = "ANALISADO"
    AWAITING_CONFIRMATION = "AGUARDANDO_CONFIRMACAO"
    ORGANIZING = "ORGANIZANDO"
    ORGANIZED = "ORGANIZADO"
    AWAITING_UPLOAD = "AGUARDANDO_UPLOAD"
    UPLOADING = "ENVIANDO"
    VERIFYING = "VERIFICANDO"
    SYNCHRONIZED = "SINCRONIZADO"
    CONFLICT = "CONFLITO"
    INTERRUPTED = "INTERROMPIDO"
    AWAITING_INTERNET = "AGUARDANDO_INTERNET"
    DEVICE_DISCONNECTED = "DISPOSITIVO_DESCONECTADO"
    INTEGRITY_FAILURE = "FALHA_DE_INTEGRIDADE"
    AWAITING_INTERVENTION = "AGUARDANDO_INTERVENCAO"
    CANCELLED = "CANCELADO"
