/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/drive/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consulta a conexão Google Drive da empresa */
        get: operations["getDriveAccount"];
        put?: never;
        post?: never;
        /** Desconecta a conta Google Drive da empresa como Proprietário */
        delete: operations["disconnectDriveAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drive/oauth/authorization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inicia a autorização Google como Proprietário */
        post: operations["startDriveAuthorization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drive/oauth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recebe o retorno de autorização do Google */
        get: operations["completeDriveAuthorization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista eventos imutáveis da empresa para Proprietários */
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista convites da empresa para Proprietários */
        get: operations["listInvitations"];
        put?: never;
        /** Cria um convite de uso único válido por sete dias */
        post: operations["createInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Aceita um convite vinculado ao e-mail autenticado */
        post: operations["acceptInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/{invitation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cancela um convite pendente */
        delete: operations["cancelInvitation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista membros da empresa para Proprietários */
        get: operations["listMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/{membership_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Altera papel ou estado preservando um Proprietário ativo */
        patch: operations["updateMembership"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/access/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Concede acesso de projeto a um Administrador ativo */
        put: operations["grantProjectAccess"];
        post?: never;
        /** Revoga acesso de projeto de um Administrador */
        delete: operations["revokeProjectAccess"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista clientes ativos da empresa selecionada */
        get: operations["listClients"];
        put?: never;
        /** Cria um cliente na empresa selecionada */
        post: operations["createClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista projetos acessíveis da empresa selecionada */
        get: operations["listProjects"];
        put?: never;
        /** Cria um projeto e concede acesso ao administrador criador */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media-files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista arquivos do catálogo acessíveis na empresa selecionada */
        get: operations["listMediaFiles"];
        put?: never;
        /** Registra um arquivo lógico e sua primeira versão física */
        post: operations["createMediaFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media-files/{media_file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Altera metadados funcionais com concorrência otimista */
        patch: operations["updateMediaFileMetadata"];
        trace?: never;
    };
    "/api/v1/media-files/{media_file_id}/metadata-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista as versões funcionais de metadados acessíveis */
        get: operations["listMediaMetadataHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media-files/{media_file_id}/metadata-history/{version}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restaura metadados como nova versão por um Proprietário */
        post: operations["restoreMediaMetadata"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista tags genéricas e personalizadas disponíveis na empresa */
        get: operations["listTags"];
        put?: never;
        /** Cria uma tag personalizada como Proprietário */
        post: operations["createCustomTag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Arquiva uma tag personalizada como Proprietário */
        delete: operations["archiveCustomTag"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media-files/{media_file_id}/tags/{tag_id}": {
        parameters: {
            query?: never;
            header: {
                "X-Company-ID": components["parameters"]["CompanyId"];
            };
            path: {
                media_file_id: string;
                tag_id: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Aplica uma tag a um arquivo acessível */
        put: operations["assignMediaFileTag"];
        post?: never;
        /** Remove uma tag de um arquivo acessível */
        delete: operations["removeMediaFileTag"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/machines/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registra a máquina ou renova sua presença autenticada */
        post: operations["recordMachineHeartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/media-files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registra de forma idempotente um arquivo organizado pelo agente */
        post: operations["ingestAgentMediaFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/media-files/{media_file_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Reconcilia uma transição técnica confirmada pelo agente local */
        patch: operations["reconcileMediaFileState"];
        trace?: never;
    };
    "/api/v1/agent/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Persiste um comando idempotente destinado a uma máquina */
        post: operations["createAgentCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/commands/{command_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Confirma recebimento, progresso ou resultado do comando */
        patch: operations["updateAgentCommandState"];
        trace?: never;
    };
    "/api/v1/agent/machines/{machine_id}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista comandos persistidos pendentes da máquina */
        get: operations["listMachineCommands"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verifica se o processo está ativo */
        get: operations["getLiveHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verifica dependências necessárias ao atendimento */
        get: operations["getReadinessHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retorna a projeção do usuário autenticado */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista empresas ativas do usuário */
        get: operations["listCompanies"];
        put?: never;
        /** Cria uma empresa e torna o usuário Proprietário */
        post: operations["createCompany"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DriveAccount: {
            connected: boolean;
            /** Format: email */
            account_email: string | null;
            /** Format: date-time */
            connected_at: string | null;
        };
        DriveAuthorization: {
            /** Format: uri */
            authorization_url: string;
        };
        CreateMediaFile: {
            /** Format: uuid */
            project_id: string;
            original_name: string;
            media_type?: string;
            size_bytes: number;
            checksum_algorithm: string;
            checksum_digest: string;
            /** Format: date-time */
            recorded_at?: string | null;
        };
        IngestAgentMediaFile: {
            /** Format: uuid */
            project_id: string;
            /** Format: uuid */
            machine_id: string;
            /** Format: uuid */
            ingestion_id: string;
            original_name: string;
            media_type?: string;
            size_bytes: number;
            checksum_algorithm: string;
            checksum_digest: string;
            /** Format: date-time */
            recorded_at?: string | null;
        };
        MediaFileCollection: {
            items: components["schemas"]["MediaFile"][];
            next_cursor: string | null;
        };
        UpdateMediaMetadata: {
            expected_version: number;
            display_name?: string;
            description?: string;
            observations?: string;
            /** Format: date-time */
            recorded_at?: string | null;
        };
        MediaFile: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            original_name: string;
            display_name: string;
            media_type: string;
            description: string;
            observations: string;
            size_bytes: number;
            checksum: {
                algorithm: string;
                digest: string;
            };
            /** Format: date-time */
            recorded_at: string | null;
            /** @enum {string} */
            status: "DESCOBERTO" | "ANALISADO" | "AGUARDANDO_CONFIRMACAO" | "ORGANIZANDO" | "ORGANIZADO" | "AGUARDANDO_UPLOAD" | "ENVIANDO" | "VERIFICANDO" | "SINCRONIZADO" | "CONFLITO" | "INTERROMPIDO" | "AGUARDANDO_INTERNET" | "DISPOSITIVO_DESCONECTADO" | "FALHA_DE_INTEGRIDADE" | "AGUARDANDO_INTERVENCAO" | "CANCELADO";
            version: number;
            tags: components["schemas"]["Tag"][];
        };
        RestoreMetadata: {
            expected_version: number;
        };
        MetadataVersionCollection: {
            items: components["schemas"]["MetadataVersion"][];
            next_version: number | null;
        };
        MetadataVersion: {
            version: number;
            /** Format: uuid */
            actor_user_id: string;
            snapshot: Record<string, never>;
            /** Format: date-time */
            created_at: string;
        };
        ReconcileMediaFileState: {
            /** Format: uuid */
            machine_id: string;
            expected_version: number;
            status: components["schemas"]["MediaFile"]["status"];
        };
        CreateTag: {
            name: string;
        };
        Tag: {
            /** Format: uuid */
            id: string;
            name: string;
            is_system: boolean;
        };
        TagCollection: {
            items: components["schemas"]["Tag"][];
        };
        MachineHeartbeat: {
            /** Format: uuid */
            installation_id: string;
            display_name: string;
            /** @enum {string} */
            os_family: "WINDOWS" | "MACOS";
            agent_version: string;
        };
        Machine: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            installation_id: string;
            display_name: string;
            os_family: string;
            agent_version: string;
            /** @enum {string} */
            status: "ONLINE" | "OFFLINE";
            /** Format: date-time */
            last_seen_at: string;
        };
        CreateAgentCommand: {
            /** Format: uuid */
            machine_id: string;
            command_type: string;
            resource_type: string;
            /** Format: uuid */
            resource_id?: string | null;
            payload: Record<string, never>;
            idempotency_key: string;
        };
        AgentCommand: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            machine_id: string;
            command_type: string;
            resource_type: string;
            /** Format: uuid */
            resource_id: string | null;
            payload: Record<string, never>;
            sequence: number;
            /** Format: uuid */
            correlation_id: string;
            /** @enum {string} */
            status: "PENDING" | "ACKNOWLEDGED" | "RUNNING" | "SUCCEEDED" | "FAILED" | "CANCELLED";
            progress_percent: number;
            result: Record<string, never>;
            failure_code: string;
            version: number;
        };
        UpdateAgentCommandState: {
            /** Format: uuid */
            machine_id: string;
            expected_version: number;
            /** @enum {string} */
            status: "ACKNOWLEDGED" | "RUNNING" | "SUCCEEDED" | "FAILED" | "CANCELLED";
            /** @default 0 */
            progress_percent: number;
            result?: Record<string, never>;
            failure_code?: string;
        };
        AgentCommandCollection: {
            items: components["schemas"]["AgentCommand"][];
        };
        AuditEventCollection: {
            items: components["schemas"]["AuditEvent"][];
            next_cursor: string | null;
        };
        AuditEvent: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            actor_user_id: string;
            event_type: string;
            action_name: string;
            description: string;
            subject_type: string;
            /** Format: uuid */
            subject_id: string;
            old_state: Record<string, never> | null;
            new_state: Record<string, never> | null;
            change_state: Record<string, never>;
            /** Format: uuid */
            correlation_id: string;
            /** Format: date-time */
            occurred_at: string;
        };
        LiveHealth: {
            /** @constant */
            status: "ok";
        };
        ReadinessHealth: {
            /** @enum {string} */
            status: "ready" | "unavailable";
            checks: {
                database: boolean;
                redis: boolean;
            };
        };
        CurrentUser: {
            /** Format: uuid */
            id: string;
        };
        CreateCompany: {
            name: string;
        };
        CompanyMembership: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            role: "OWNER" | "ADMINISTRATOR";
            version: number;
        };
        CompanyCollection: {
            items: components["schemas"]["CompanyMembership"][];
            next_cursor: string | null;
        };
        Problem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            code: string;
            detail: string;
            /** Format: uuid */
            trace_id: string;
        };
    };
    responses: {
        /** @description Autenticação necessária */
        AuthenticationRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Dados inválidos */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        CompanyId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getDriveAccount: {
        parameters: {
            query?: never;
            header: {
                "X-Company-ID": components["parameters"]["CompanyId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Estado da conexão */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriveAccount"];
                };
            };
        };
    };
    disconnectDriveAccount: {
        parameters: {
            query?: never;
            header: {
                "X-Company-ID": components["parameters"]["CompanyId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conta desconectada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    startDriveAuthorization: {
        parameters: {
            query?: never;
            header: {
                "X-Company-ID": components["parameters"]["CompanyId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description URL oficial de autorização do Google */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriveAuthorization"];
                };
            };
            /** @description Credenciais OAuth ainda não configuradas */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    completeDriveAuthorization: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
                error?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retorno ao frontend com resultado sem credenciais */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAuditEvents: {
        parameters: {
            query?: never;
            header: {
                "X-Company-ID": components["parameters"]["CompanyId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Eventos de auditoria da empresa */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventCollection"];
                };
            };
        };
    };
    listInvitations: {
        parameters: {
            query?: never;
            header: {
                "X-Company-ID": components["parameters"]["CompanyId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Convites da empresa */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createInvitation: {
        parameters: {
            query?: never;
            header: {
                "X-Company-ID": components["parameters"]["CompanyId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Convite criado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    acceptInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Convite aceito */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancelInvitation: {
        parameters: {
            query?: never;
            header: {
                "X-Company-ID": components["parameters"]["CompanyId"];
            };
            path: {
                invitation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Convite cancelado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listMembers: {
        parameters: {
            query?: never;
            header: {
                "X-Company-ID": components["parameters"]["CompanyId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Membros da empresa */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateMembership: {
        parameters: {
            query?: never;
            header: {
                "X-Company-ID": components["parameters"]["CompanyId"];
            };
            path: {
                membership_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vínculo atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    grantProjectAccess: {
        parameters: {
            query?: never;
            header: {
                "X-Company-ID": components["parameters"]["CompanyId"];
            };
            path: {
                project_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Acesso concedido */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revokeProjectAccess: {
        parameters: {
            query?: never;
            header: {
                "X-Company-ID": components["parameters"]["CompanyId"];
            };
            path: {
                project_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Acesso revogado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listClients: {
        parameters: {
            query?: never;
            header: {
                "X-Company-ID": components["parameters"]["CompanyId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Clientes disponíveis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createClient: {
        parameters: {
            query?: never;
            header: {
                "X-Company-ID": components["parameters"]["CompanyId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cliente criado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header: {
                "X-Company-ID": components["parameters"]["CompanyId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projetos disponíveis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header: {
                "X-Company-ID": components["parameters"]["CompanyId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projeto criado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listMediaFiles: {
        parameters: {
            query?: {
                q?: string;
                project_id?: string;
                status?: string;
                tag_id?: string;
                extension?: string;
                media_type?: string;
                min_size_bytes?: number;
                max_size_bytes?: number;
                recorded_from?: string;
                recorded_to?: string;
                created_by_user_id?: string;
                cursor?: string;
                limit?: number;
            };
            header: {
                "X-Company-ID": components["parameters"]["CompanyId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Arquivos acessíveis do catálogo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaFileCollection"];
                };
            };
        };
    };
    createMediaFile: {
        parameters: {
            query?: never;
            header: {
                "X-Company-ID": components["parameters"]["CompanyId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMediaFile"];
            };
        };
        responses: {
            /** @description Arquivo registrado no catálogo */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaFile"];
                };
            };
            400: components["responses"]["ValidationError"];
        };
    };
    updateMediaFileMetadata: {
        parameters: {
            query?: never;
            header: {
                "X-Company-ID": components["parameters"]["CompanyId"];
            };
            path: {
                media_file_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMediaMetadata"];
            };
        };
        responses: {
            /** @description Metadados atualizados */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaFile"];
                };
            };
            /** @description Versão desatualizada */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listMediaMetadataHistory: {
        parameters: {
            query?: {
                after_version?: number;
                limit?: number;
            };
            header: {
                "X-Company-ID": components["parameters"]["CompanyId"];
            };
            path: {
                media_file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Histórico funcional do arquivo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetadataVersionCollection"];
                };
            };
            /** @description Arquivo não encontrado no contexto autorizado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    restoreMediaMetadata: {
        parameters: {
            query?: never;
            header: {
                "X-Company-ID": components["parameters"]["CompanyId"];
            };
            path: {
                media_file_id: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestoreMetadata"];
            };
        };
        responses: {
            /** @description Metadados restaurados ou já equivalentes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaFile"];
                };
            };
            /** @description Papel sem permissão para restaurar */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Arquivo ou versão não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Versão atual desatualizada */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listTags: {
        parameters: {
            query?: never;
            header: {
                "X-Company-ID": components["parameters"]["CompanyId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tags disponíveis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagCollection"];
                };
            };
        };
    };
    createCustomTag: {
        parameters: {
            query?: never;
            header: {
                "X-Company-ID": components["parameters"]["CompanyId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTag"];
            };
        };
        responses: {
            /** @description Tag personalizada criada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            /** @description Papel sem permissão para gerenciar tags */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    archiveCustomTag: {
        parameters: {
            query?: never;
            header: {
                "X-Company-ID": components["parameters"]["CompanyId"];
            };
            path: {
                tag_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tag arquivada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Tag personalizada não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    assignMediaFileTag: {
        parameters: {
            query?: never;
            header: {
                "X-Company-ID": components["parameters"]["CompanyId"];
            };
            path: {
                media_file_id: string;
                tag_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tag aplicada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Arquivo ou tag não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    removeMediaFileTag: {
        parameters: {
            query?: never;
            header: {
                "X-Company-ID": components["parameters"]["CompanyId"];
            };
            path: {
                media_file_id: string;
                tag_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tag removida */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Arquivo não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    recordMachineHeartbeat: {
        parameters: {
            query?: never;
            header: {
                "X-Company-ID": components["parameters"]["CompanyId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MachineHeartbeat"];
            };
        };
        responses: {
            /** @description Presença registrada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Machine"];
                };
            };
        };
    };
    ingestAgentMediaFile: {
        parameters: {
            query?: never;
            header: {
                "X-Company-ID": components["parameters"]["CompanyId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestAgentMediaFile"];
            };
        };
        responses: {
            /** @description Ingestão existente devolvida sem duplicação */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaFile"];
                };
            };
            /** @description Arquivo registrado no catálogo */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaFile"];
                };
            };
            400: components["responses"]["ValidationError"];
            /** @description Máquina não encontrada no contexto autorizado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Identificador de ingestão usado com outros dados */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reconcileMediaFileState: {
        parameters: {
            query?: never;
            header: {
                "X-Company-ID": components["parameters"]["CompanyId"];
            };
            path: {
                media_file_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReconcileMediaFileState"];
            };
        };
        responses: {
            /** @description Estado atual do arquivo, inclusive em repetição idempotente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaFile"];
                };
            };
            /** @description Transição técnica inválida */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Arquivo ou máquina não encontrado no contexto autorizado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Versão do arquivo desatualizada */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createAgentCommand: {
        parameters: {
            query?: never;
            header: {
                "X-Company-ID": components["parameters"]["CompanyId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAgentCommand"];
            };
        };
        responses: {
            /** @description Comando idempotente já existente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Comando criado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentCommand"];
                };
            };
            /** @description Chave reutilizada com conteúdo diferente */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateAgentCommandState: {
        parameters: {
            query?: never;
            header: {
                "X-Company-ID": components["parameters"]["CompanyId"];
            };
            path: {
                command_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAgentCommandState"];
            };
        };
        responses: {
            /** @description Estado atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentCommand"];
                };
            };
            /** @description Transição inválida */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Versão do comando desatualizada */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listMachineCommands: {
        parameters: {
            query?: {
                after_sequence?: number;
                limit?: number;
            };
            header: {
                "X-Company-ID": components["parameters"]["CompanyId"];
            };
            path: {
                machine_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comandos ainda executáveis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentCommandCollection"];
                };
            };
            /** @description Máquina não encontrada na empresa */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getLiveHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Processo ativo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveHealth"];
                };
            };
        };
    };
    getReadinessHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Serviço pronto */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessHealth"];
                };
            };
            /** @description Dependência indisponível */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessHealth"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usuário autenticado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            401: components["responses"]["AuthenticationRequired"];
        };
    };
    listCompanies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Empresas disponíveis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyCollection"];
                };
            };
            401: components["responses"]["AuthenticationRequired"];
        };
    };
    createCompany: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCompany"];
            };
        };
        responses: {
            /** @description Empresa criada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyMembership"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["AuthenticationRequired"];
        };
    };
}
